#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 3 ]; then 
echo "usage v1: eap_run_bam_to_bw_uniq_minus in.bam chromFile outUniqMinus.bw"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Expected versions:
# package(tool): uniformAnalysis(eap_run_bam_to_bw_uniq_minus) [version: v1.0(v1)]
# tool: samtools [version: 0.1.19-96b5f2294a]
# package(tool): GeorgiScripts(makewigglefromBAM-NH.py) [version: Last modified 09/06/2013]
# package(tool): python(python2.7) [version: 2.7.6]
# package(tool): ucscUtils(bedGraphToBigWig) [version: v302(v4)]

# Label parameters and copying input(s) to local tmp dir
cp $1 tmp.bam            # INPUT: alignment bam
cp ${1}.bai tmp.bam.bai  # INPUT: alignment bam index
chromFile=$2             # Chrom info file for the genome and gender
outUniqMinusBw=$3        # OUTPUT: bigWig signal of uniquely mapped minus-strand reads

# generate plus strand wig file from uniquely mapped reads from bam
python2.7 ${EAP_TOOLS_DIR}/makewigglefromBAM-NH.py --- tmp.bam ${chromFile} tmpUniqMinusNeg.bg \
          -stranded - -nomulti -RPM -notitle -fragments second-read-strand
perl -pe 's/-//g' < tmpUniqMinusNeg.bg > tmpUniqMinus.bg 
bedGraphToBigWig tmpUniqMinus.bg ${chromFile} out_uniq_minus.bw

# remove some larger files:
rm tmpUniqMinusNeg.bg tmp.bam tmp.bam.bai
#rm tmpUniqMinus.bg 

# deliver results:
mv out_uniq_minus.bw ${outUniqMinusBw} 
