#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 4 ]; then 
echo "usage v1: eap_run_star_long_se star-genomeDir libraryId reads.fq out.bam"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Copy reads to local tmp file since will be making several passes
cp $3 tmp.fq.gz

# samtools command, library and COfile will be folded into bam header
samtoolsCommand="samtools view -buS - | samtools sort -m20G -@4 - sorted"
libraryId="@CO\tLIBID:$2"
echo -e $libraryId > COfile.txt
cat $1/COfile.txt >> COfile.txt

# Using $1 as an reference genome, align reads ($2)
STAR --genomeDir $1 --readFilesIn tmp.fq.gz                                         \
     --readFilesCommand zcat --runThreadN 12 --genomeLoad LoadAndRemove              \
     --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1       \
     --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04                     \
     --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000            \
     --outSAMheaderCommentFile COfile.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate   \
     --outSAMheaderPG @PG ID:Samtools PN:Samtools CL:"$samtoolsCommand" PP:STAR VN:VN:0.1.19-96b5f2294a \
     --outSAMunmapped Within --outFilterType BySJout --outStd SAM | samtools view -buS - | \
     samtools sort -m20G -@4 - sorted

### TODO: Find appropriate accession for library.  Perhaps it is beyond scope.
### echo "@CO LIBID:ENCLB175ZZZ" >> newHeader.sam 

rm tmp.fq.gz
mv sorted.bam $4

# make sure star log is recorded.
cat Log.final.out

