#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 3 ];
then echo "usage v1: eap_run_slx_bwa_se bwa-index solexa-reads.fq out.bam"
echo Makes temp files so should be run in a freshly created directory .
exit -1; fi

# Covert fastq in $2 to sanger format quality scores
edwSolexaToSangerFastq $2 tmp.fq

# Using $1 as an index, align reads putting output in $3
bwa aln -t 4 $1 tmp.fq > tmp.sai
bwa samse $1 tmp.sai tmp.fq > tmp.sam
samtools view -S -b tmp.sam > tmp.bam
samtools sort tmp.bam sorted
mv sorted.bam $3

# Remove some big boring files.
rm tmp.fq tmp.sai tmp.sam tmp.bam

