#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 7 ];
then echo "usage v1: eap_run_bismark bismark-index reads.fq out.sam outstats.txt CG.bedGraph CHG.bedGraph CHH.bedGraph"
echo Makes temp files so should be run in a freshly created directory .
exit -1; fi

fastqMottTrim $2 trimmed.fq

/hive/groups/encode/3/tools/bismark/bismark_v0.10.1/bismark -n 1 -l 28 $1 trimmed.fq -o . --path_to_bowtie /hive/groups/encode/3/tools/bowtie/bowtie-1.0.0/ --temp_dir ./

/hive/groups/encode/3/tools/bismark/bismark_v0.10.1/bismark_methylation_extractor -s --comprehensive --cytosine_report --CX_context --output . --zero_based --genome_folder $1 trimmed.fq_bismark.sam

cxrepo-bed.py trimmed.fq_bismark.CX_report.txt

mv "trimmed.fq_bismark.sam" $3
mv "trimmed.fq_bismark_SE_report.txt" $4

mv "CG_trimmed.fq_bismark_pe.CX_report.txt" $5
mv "CHG_trimmed.fq_bismark_pe.CX_report.txt" $6
mv "CHH_trimmed.fq_bismark_pe.CX_report.txt" $7
