#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 8 ]; then 
echo "usage v2: eap_run_star_long_se starRefIndexDir chromFile libraryId read1.fq.gz \\"
echo "          outGenome.bam outAnnotation.bam outAll.bw outUniq.bw"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Expected versions:
# package(tool): uniformAnalysis(eap_run_star_long_se) [version: v1.0(v2)]
# package(tool): STAR [version: 2.3.1z8(2.3.1z8_r447)]
# tool: samtools [version: 0.1.19-96b5f2294a]
# package(tool): ucscUtils(bedGraphToBigWig) [version: v293(v4)]

# Label parameters and copying input(s) to local tmp dir
starRefIndexDir=$1     # Directory containing STAR generated index on genome and spike-in
chromFile=$2           # Chrom info file for the genome and gender
libraryId=$3           # Accession ID (or other identifier) of bio-sample used to generate fastq(s)
cp $4 reads.fq.gz      # INPUT: gzipped fastq of unpaired reads
outGenomeBam=$5        # OUTPUT: reads aligned to whole genome by STAR (*.bai is also generated)
outAnnotationBam=$6    # OUTPUT: reads aligned to gencode annotation by STAR
outAllBw=$7            # OUTPUT: bigWig signal of unique and multi-mapped unstranded reads
outUniqBw=$8           # OUTPUT: bigWig signal of uniquely mapped unstranded reads

# library and COfile will be folded into bam header
libraryComment="@CO\tLIBID:${libraryId}"
echo -e ${libraryComment} > COfile.txt
cat ${starRefIndexDir}/COfile.txt >> COfile.txt

# Note: in order to run on cluster, using:
# - STAR symlinked to STARstatic, 
# - --genomeLoad NoSharedMemory (instead of LoadAndRemove) 
# - 32g ram, 12 cpus.

# Run star for unpaired and unstranded reads.
STAR --genomeDir ${starRefIndexDir} --readFilesIn reads.fq.gz                    \
     --readFilesCommand zcat --runThreadN 12 --genomeLoad NoSharedMemory          \
     --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1    \
     --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04                  \
     --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000         \
     --outSAMheaderCommentFile COfile.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate   \
     --outSAMunmapped Within --outFilterType BySJout --outSAMattributes NH HI AS NM MD \
     --outWigType bedGraph --outWigStrand Unstranded --outSAMstrandField intronMotif    \
     --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM

samtools index Aligned.sortedByCoord.out.bam
# samtools index Aligned.toTranscriptome.out.bam # No need and not sorted so indexing fails

# Convert bedGraph to bigWigs.  Spike-ins must be excluded and piping doesn't work
grep ^chr Signal.UniqueMultiple.str1.out.bg > signalAll.bg
bedGraphToBigWig signalAll.bg ${chromFile}    signalAll.bw
grep ^chr Signal.Unique.str1.out.bg         > signalUniq.bg
bedGraphToBigWig signalUniq.bg ${chromFile}   signalUniq.bw

# remove some larger files:
rm reads.fq.gz
rm signal*.bg
#rm Signal.*.bg

# deliver results:
mv Aligned.sortedByCoord.out.bam ${outStarGenomeBam}
mv Aligned.sortedByCoord.out.bam.bai ${outStarGenomeBam}.bai
mv Aligned.toTranscriptome.out.bam ${outAnnotationBam}
# mv Aligned.toTranscriptome.out.bam.bai ${outAnnotationBam}.bai
mv signalAll.bw ${outAllBw}
mv signalUniq.bw ${outUniqBw}

# make sure star log is recorded.
cat Log.final.out

