#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 3 ]; then 
echo "usage v1: eap_run_bam_to_bw_all_plus in.bam chrom.file out_all_plus.bw"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Expected versions:
# package(tool): ucscUtils(eap_run_bam_to_bw_all_plus) [version: v293(v1)]
# tool: samtools [version: 0.1.19-96b5f2294a]
# package(tool): GeorgiScripts(makewigglefromBAM-NH.py) [version: Last modified 09/06/2013]
# package(tool): python(python2.7) [version: 2.7.6]
# package(tool): ucscUtils(wigToBigWig) [version: v293(v4)]

# Copy reads and index to local tmp file since will be making several passes
cp $1 tmp.bam
cp ${1}.bai tmp.bam.bai

# generate plus strand wig file from all mapped reads from bam and using chrom.file ($2)
python2.7 ${EAP_TOOLS_DIR}/makewigglefromBAM-NH.py --- tmp.bam $2 tmpAllPlus.wig -stranded + \
          -RPM -notitle -fragments second-read-strand
wigToBigWig tmpAllPlus.wig $2 out_all_plus.bw

# remove some larger files:
rm tmpAllPlus.wig tmp.bam tmp.bam.bai

# deliver results:
mv out_all_plus.bw $3 
