#!/bin/bash -e
# Run bash with -e exit on first error

# Check command line and provide usage and version information
if [ $# -ne 2 ];
then echo "usage v1: eap_bam_sort unsorted.bam sorted_by_chrom.bam
echo "Make new bam sorted by chromosome.
exit -1; fi

samtools sort $1 $2
mv $2.bam $2

