#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 5 ]; then 
#echo "usage v1: eap_pre_rsem_index genomeRef.fa spikeIn.fa annotation.gtf resemRefDir \\"
echo "usage v1: eap_pre_rsem_index genomeRef.fa annotation.gtf resemRefDir \\"
echo "          rsemIndexPrefix outIndex.tgz"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Expected versions:
# package(tool): uniformAnalysis(eap_pre_rsem_index) [version: v1.0(v1)]
# package(tool): RSEM(rsem-calculate-expression) [version: v1.2.12]
# tool: bowtie2 [version: 2.1.0]

# Label parameters and copying input(s) to local tmp dir
genomeRefFa=$1            # INPUT: Full path to genome reference in fa format (e.g. female.hg19.fa)
annotationGtf=$2          # INPUT: Full path to gene/transcript annotation (e.g. gencode.v19.gtf)
rsemRefDir=$3             # Directory to contain RSEM index on genome,spike-in grouped by prefix
rsemIndexPrefix=$4        # Prefix to be applied to all genome index files (just like RSEM wants)
outRsemIndexTgz=$5        # OUTPUT: archive of genome index files that may be accessioned

# Make target dir and build index files
mkdir -p ${rsemRefDir}
${EAP_TOOLS_DIR}/RSEM-1.2.12/rsem-prepare-reference --no-polyA --no-bowtie --no-ntog \
             --gtf ${annotationGtf} ${genomeRefFa} ${rsemRefDir}/${rsemIndexPrefix} 

# Attempt to make bamCommentLines.txt, which should be reviewed. NOTE tabs handled by assignment.
refComment="@CO\tREFID:$(basename ${genomeRefFa%.*})"
annotationComment="@CO\tANNID:$(basename ${annotationGtf})"
spikeInComment="@CO\tSPIKEID:$(basename ${spikeInFa%.*})"
echo ${refComment} > ${rsemIndexPrefix}_bamCommentLines.txt
echo ${annotationComment} >> ${rsemIndexPrefix}_bamCommentLines.txt
echo ${spikeInComment} >> ${rsemIndexPrefix}_bamCommentLines.txt

# TODO: bowtie will expect single ${rsemIndexPrefix}.fa containing genome and spike-in
#       This is generated on first run of RSEM alignment and should be move into place 

# tar up index set for accessioning
pushd ${rsemRefDir}
tar -czf rsemIndex.tgz ${rsemIndexPrefix}*
popd

# deliver results:
mv rsemIndex.tgz ${outRsemIndexTgz}

# Command lines run:
# female.hg19/gencode.v19:
# eap_pre_rsem_index ${EAP_REF_DIR}/female.hg19/female.hg19.fa \
#                   ${EAP_REF_DIR}/hg19/gencode.v19.annotation.gtf \
#                  ${EAP_REF_DIR}/female.hg19/rsemData rsem \
#                 ${EAP_REF_DIR}/female.hg19/rsemData/rsem_hg19FemaleGencodeV19.tgz
# male.hg19/gencode.v19:
# eap_pre_rsem_index ${EAP_REF_DIR}/male.hg19/male.hg19.fa \
#                   ${EAP_REF_DIR}/hg19/gencode.v19.annotation.gtf \
#                  ${EAP_REF_DIR}/male.hg19/rsemData rsem \
#                 ${EAP_REF_DIR}/male.hg19/rsemData/rsem_hg19MaleGencodeV19.tgz
