#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 4 ];
then echo "usage v2: eap_run_macs2_dnase_pe target in.bam out.narrowPeak.bigBed out.bigWig"
echo target is ucsc database ID - hg19 or hg38 or mm10 most commonly at time of writing.
echo Makes temp files so should be run in a freshly created directory .
exit -1; fi

# Run macs on $2. The macs output will be in tmp_* 
macs2 callpeak -t $2 -B -n tmp 

# Convert macs tmp_peaks.xls output to narrowPeak.bb format in $3, checking chromosome coords vs $1
eap_macs2_xls_to_narrowPeak tmp_peaks.xls >tmp.narrowPeak
eap_narrowPeak_to_bigBed $1 tmp.narrowPeak $3

# Convert tmp_treat_pileup.bdg to bigWig in $4, checking chrom coords against $1
bedGraphToBigWig tmp_treat_pileup.bdg /hive/groups/encode/encode3/encValData/$1/chrom.sizes tmp.bigWig
mv tmp.bigWig $4

# Remove some big boring temp files
rm tmp_*.bdg
