#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 6 ]; then 
echo "usage v1: eap_run_rsem_long_pe starRefIndexDir rsemRefPath read1.fq.gz read2.fq.gz \\"
echo "          outGene.results outIsoform.results"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Expected versions:
# package(tool): uniformAnalysis(eap_run_rsem_long_pe) [version: v1.0(v1)]
# tool: STAR [version: 2.4.0]
# tool: samtools [version: 0.1.19-96b5f2294a]
# package(tool): RSEM(rsem-calculate-expression) [version: v1.2.12]

# Label parameters and copying input(s) to local tmp dir
starRefIndexDir=$1     # Directory containing STAR generated index on genome and spike-in
rsemRefPath=$2         # Directory/prefix of RSEM (STAR) generated index on transcriptome
cp $3 read1.fq.gz      # INPUT: gzipped fastq of read1 of paired-end reads
cp $4 read2.fq.gz      # INPUT: gzipped fastq of read2 of paired-end reads
outGeneResults=$5      # OUTPUT: RSEM quantification of annotated genes
outIsoformResults=$6   # OUTPUT: RSEM quantification of transcripts

# Run star on paired-end, stranded fastq's to get transcriptome alignment.
STAR --genomeDir ${starRefIndexDir} --readFilesIn read1.fq.gz read2.fq.gz           \
     --readFilesCommand zcat --runThreadN 12 --genomeLoad NoSharedMemory             \
     --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1       \
     --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04                     \
     --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000            \
     --outSAMattributes NH HI --outSAMtype None --quantMode TranscriptomeSAM

# Assume we need the bam indexed.
samtools index AlignedToTranscriptome.out.bam

# Run RSEM on the STAR transcriptome alignment
${EAP_TOOLS_DIR}/rsem/rsem-calculate-expression --bam --estimate-rspd --calc-ci --no-bam-output \
                                 -p 12 --ci-memory 30000 --paired-end --forward-prob 0 \
                                 AlignedToTranscriptome.out.bam ${rsemRefPath} rsemOut >& Log.rsem


### # Using $1 as location of genome indexes, ERCC as base containing the spikein index, align reads
### ${EAP_TOOLS_DIR}/rsem/rsem-calculate-expression -p 8 --bowtie2 --paired-end \
###        --forward-prob 0 --estimate-rspd --calc-ci --ci-memory 10000 \
###        read1.fq.gz read2.fq.gz $1 rsemOut

# remove some larger files:
rm read1.fq.gz read2.fq.gz
#rm AlignedToTranscriptome.out.bam*

# deliver results:
mv rsemOut.genes.results ${outGeneResults}
mv rsemOut.isoforms.results ${outIsoformResults}

