#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 5 ]; then 
echo "usage v1: eap_run_tophat_long_pe tophatRefDir spikeInSet read1.fq read2.fq out.bam"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Copy reads to local tmp file since will be making several passes
cp $3 tmp1.fq.gz
cp $4 tmp2.fq.gz

# Using $1 as location of genome indexes, $2 as subdir containing the spikein index, align reads
### Temporary use of if while developing:
if [ $2 == 'ERCC' ]; then
    tophat --no-discordant --no-mixed -p 8 -z0 --min-intron-length 20 --max-intron-length 1000000 \
           --read-mismatches 4 --read-edit-dist 4 --max-multihits 20 --library-type fr-firststrand \
           --transcriptome-index $1annotation/gencode.v19 \
       --min-anchor-length 8 --splice-mismatches 0 --read-gap-length 2 \
       --mate-inner-dist 50 --mate-std-dev 20 --segment-length 25 \
       --b2-L 20 --b2-N 0 --b2-D 15 --b2-R 2 \
           $1$2 tmp1.fq.gz tmp2.fq.gz
else
    tophat --no-discordant --no-mixed -p 8 -z0 --min-intron-length 20 --max-intron-length 1000000 \
           --read-mismatches 4 --read-edit-dist 4 --max-multihits 20 \
           --transcriptome-index $1annotation/gencode.v19 \
       --min-anchor-length 8 --splice-mismatches 0 --read-gap-length 2 \
       --mate-inner-dist 50 --mate-std-dev 20 --segment-length 25 \
       --b2-L 20 --b2-N 0 --b2-D 15 --b2-R 2 \
           $1$2 tmp1.fq.gz tmp2.fq.gz
fi

# sort
samtools view -bu tophat_out/accepted_hits.bam | samtools sort -m20G - sorted 
    
# Building a new header
HD="@HD\tVN:1.4\tSO:coordinate" 
stCommand="samtools view -buS - | samtools sort -m20G - sorted"
newPG="@PG ID:Samtools PN:Samtools CL:"$stCommand" PP:Tophat VN:VN:0.1.19-96b5f2294a"

samtools view -H -S sorted.bam | \
gawk -v HD="$HD" -v newPG="$newPG" -v headDone=0 \
   '{     if ($0 ~ /^@PG/) {PG=$0} 
     else if ($0 ~ /^@HD/) {} 
     else {if(!headDone) {print HD; 
                          print newPG"\n"PG; 
                          print $0; headDone = 1} 
           else {print $0}}}' > newHeader.sam
           
### # Add reference genome specific accessions to header
cat $1/$2_COfile.txt >> newHeader.sam

### TODO: Find appropriate accession for library.  Perhaps it is beyond scope.
### echo "@CO LIBID:ENCLB175ZZZ" >> newHeader.sam 

samtools reheader newHeader.sam sorted.bam > reheaded.bam

### #rm tmp1.fq.gz tmp2.fq.gz sorted.bam

mv reheaded.bam $5

### # make sure tophat log is recorded.
### cat tophat_out/logs/run.log
### cat tophat_out/logs/tophat.log

