#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 5 ]; then 
echo "usage v1: eap_run_rsem_long_se starRefIndexDir rsemRefPath reads.fq.gz \\"
echo "          outGene.results outIsoform.results"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Expected versions:
# package(tool): uniformAnalysis(eap_run_rsem_long_pe) [version: v1.0(v1)]
# tool: STAR [version: 2.4.0]
# tool: samtools [version: 0.1.19-96b5f2294a]
# package(tool): RSEM(rsem-calculate-expression) [version: v1.2.12]

# Label parameters and copying input(s) to local tmp dir
starRefIndexDir=$1     # Directory containing STAR generated index on genome and spike-in
rsemRefPath=$2         # Directory/prefix of RSEM (STAR) generated index on transcriptome
cp $3 reads.fq.gz      # INPUT: gzipped fastq of unpaired reads
outGeneResults=$4      # OUTPUT: RSEM quantification of annotated genes
outIsoformResults=$5   # OUTPUT: RSEM quantification of transcripts

# Run star on unpaired, unstranded fastq to get transcriptome alignment.
STAR --genomeDir ${starRefIndexDir} --readFilesIn reads.fq.gz                       \
     --readFilesCommand zcat --runThreadN 12 --genomeLoad NoSharedMemory             \
     --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1       \
     --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04                     \
     --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000            \
     --outSAMattributes NH HI --outSAMtype None --quantMode TranscriptomeSAM

# Assume we need the bam indexed.
samtools index AlignedToTranscriptome.out.bam

# Run RSEM on the STAR transcriptome alignment
${EAP_TOOLS_DIR}/rsem/rsem-calculate-expression --bam --estimate-rspd --calc-ci --no-bam-output \
                                 -p 12 --ci-memory 30000 \
                                 AlignedToTranscriptome.out.bam ${rsemRefPath} rsemOut >& Log.rsem

# From Colin Dewey:
# --no-bam-output # if we are not going to do anything with the RSEM alignments, give this option

# Using $1 as location of genome indexes, ERCC as base containing the spikein index, align reads
${EAP_TOOLS_DIR}/rsem/rsem-calculate-expression -p 8 --bowtie2 \
       --forward-prob 0 --estimate-rspd --calc-ci --ci-memory 10000 reads.fq.gz $1 rsemOut

# remove some larger files:
rm reads.fq.gz
#rm AlignedToTranscriptome.out.bam*

# deliver results:
mv rsemOut.genes.results ${outGeneResults}
mv rsemOut.isoforms.results ${outIsoformResults}

