#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
#
# This script calculates numbers related to how alignments on opposite strands relate
# to peaks.  The arguments are:
#  $1 - a bam file to analyse
#  $2 - where to put one line of statistical output

# Check command line and provide usage and version information
if [ $# -ne 2 ];
then echo "usage v1: eap_run_phantom_peak_spp input.bam output.tab"
exit -1; fi

# Call R to do the calcs on the bam file
Rscript /hive/groups/encode/encode3/tools/phantompeakqualtools/run_spp.R -x=-500:-1 -s=-500:5:1500 -c=$1 -out=temp.tab

# Move output to a more permanent location
mv temp.tab $2
