#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 4 ]; then 
echo "usage v1: eap_run_rsem_long_pe rsemRefPath inAnnotation.bam \\"
echo "          outGene.results outIsoform.results"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Expected versions:
# package(tool): uniformAnalysis(eap_run_rsem_long_pe) [version: v1.0(v1)]
# tool: STAR [version: 2.4.0]
# tool: samtools [version: 0.1.19-96b5f2294a]
# package(tool): RSEM(rsem-calculate-expression) [version: v1.2.14]

# Label parameters and copying input(s) to local tmp dir
rsemRefPath=$1         # Directory/prefix of RSEM (STAR) generated index on transcriptome
cp $2 inAnnotation.bam # INPUT: Gencode annotation aligned bam file
outGeneResults=$3      # OUTPUT: RSEM quantification of annotated genes
outIsoformResults=$4   # OUTPUT: RSEM quantification of transcripts

# Assume the bam index is also needed
# cp ${2}.bai transcript.bam .bai  # No need and not sorted or produced.

# Run RSEM on the STAR transcriptome alignment
${EAP_TOOLS_DIR}/rsem/rsem-calculate-expression --bam --estimate-rspd --calc-ci --no-bam-output \
                                 -p 12 --ci-memory 30000 --paired-end --forward-prob 0 \
                                 inAnnotation.bam ${rsemRefPath} rsemOut

# remove some larger files:
rm inAnnotation.bam

# deliver results:
mv rsemOut.genes.results ${outGeneResults}
mv rsemOut.isoforms.results ${outIsoformResults}

