#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 3 ]; then 
echo "usage v1: eap_run_bam_to_bw_uniq_plus in.bam chrom.file out.bw"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Copy reads and index to local tmp file since will be making several passes
cp $1 tmp.bam
cp ${1}.bai tmp.bam.bai

# generate plus strand wig file from uniquely mapped reads from bam and using chrom.file ($2)
python2.7 ${EAP_TOOLS_DIR}/makewigglefromBAM-NH.py --- tmp.bam $2 tmpUniqPlus.wig -stranded + \
          -nomulti -RPM -notitle -fragments second-read-strand
wigToBigWig tmpUniqPlus.wig $2 tmpUniqPlus.bw
rm tmpUniqPlus.wig

mv tmpUniqPlus.bw $3 
