#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 8 ];
then echo "usage v1: eap_run_bismark bismark-index reads1.fq reads2.fq out.sam outstats.txt CG.bedGraph CHG.bedGraph CHH.bedGraph"
echo Makes temp files so should be run in a freshly created directory .
exit -1; fi

fastqMottTrim $2 $3 trimmedRd1.fq trimmedRd2.fq

/hive/groups/encode/3/tools/bismark/bismark_v0.10.1/bismark -n 1 -l 28 $1 -1 trimmedRd1.fq -2 trimmedRd2.fq -o . --path_to_bowtie /hive/groups/encode/3/tools/bowtie/bowtie-1.0.0/ --temp_dir ./

/hive/groups/encode/3/tools/bismark/bismark_v0.10.1/bismark_methylation_extractor -p -no_overlap --comprehensive --cytosine_report --CX_context --output . --zero_based --genome_folder $1 trimmedRd1.fq_bismark_pe.sam

cxrepo-bed.py trimmedRd1.fq_bismark_pe.CX_report.txt

mv "trimmedRd1.fq_bismark_pe.sam" $4
mv "trimmedRd1.fq_bismark_PE_report.txt" $5

mv "CG_trimmedRd1.fq_bismark_pe.CX_report.txt" $6
mv "CHG_trimmedRd1.fq_bismark_pe.CX_report.txt" $7
mv "CHH_trimmedRd1.fq_bismark_pe.CX_report.txt" $8
