#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 4 ];
then echo "usage v1: eap_run_bismark bismark-index reads.fq out.sam outstats.txt"
echo Makes temp files so should be run in a freshly created directory .
exit -1; fi

/cluster/home/mmaddren/bin/x86_64/fastqMottTrim $2 trimmed.fq

/hive/groups/encode/3/tools/bismark/bismark_v0.10.1/bismark -n 1 -l 28 $1 trimmed.fq -o . --path_to_bowtie /hive/groups/encode/3/tools/bowtie/bowtie-1.0.0/ --temp_dir ./

/hive/groups/encode/3/tools/bismark/bismark_v0.10.1/bismark_methylation_extractor -s --comprehensive  --comprehensive --cytosine_report --CX_context --output . --zero_based --genome_folder $1 trimmed.fq_bismark.sam

python /cluster/home/mmaddren/grad/pipeline/methyl/methyl2/script/cxrepo-bed.py trimmed.fq_bismark.CX_report.txt

mv "trimmed.fq_bismark.sam" $3
mv "trimmed.fq_bismark_SE_report.txt" $4

# not sure where we want these
#mv "CG_trimmed.fq_bismark_pe.CX_report.txt" $6
#mv "CHG_trimmed.fq_bismark_pe.CX_report.txt" $7
#mv "CHH_trimmed.fq_bismark_pe.CX_report.txt" $8