#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 6 ]; then 
echo "usage v1: eap_run_rna_bam_to_bigwigs in.bam chrom.file outUniqPlus.bw outUniqMinus.bw outAllPlus.bw outAllMinus.bw"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Copy reads to local tmp file since will be making several passes
cp $1 tmp.bam

# index that bam
samtools index tmp.bam

# generate plus strand uniquely mapped wig file
python2.7 ${EAP_TOOLS_DIR}/makewigglefromBAM-NH.py --- tmp.bam $2 outUniqPlus.wig -stranded + \
          -nomulti -RPM -notitle -fragments second-read-strand
wigToBigWig outUniqPlus.wig $2 outUniqPlus.bw
rm outUniqPlus.wig

# generate minus strand uniquely mapped wig file
python2.7 ${EAP_TOOLS_DIR}/makewigglefromBAM-NH.py --- tmp.bam $2 outUniqMinus.wig -stranded - \
          -nomulti -RPM -notitle -fragments second-read-strand
perl -pe 's/-//g' < outUniqMinus.wig | wigToBigWig stdin $2 outUniqMinus.bw
rm outUniqMinus.wig

# generate plus strand all (uniq+multi) mapped wig file
python2.7 ${EAP_TOOLS_DIR}/makewigglefromBAM-NH.py --- tmp.bam $2 outAllPlus.wig -stranded + \
          -RPM -notitle -fragments second-read-strand
wigToBigWig outAllPlus.wig $2 outAllPlus.bw
rm outAllPlus.wig

# generate minus strand all (uniq+multi) mapped wig file
python2.7 ${EAP_TOOLS_DIR}/makewigglefromBAM-NH.py --- tmp.bam $2 outAllMinus.wig -stranded - \
          -RPM -notitle -fragments second-read-strand
perl -pe 's/-//g' < outAllMinus.wig | wigToBigWig stdin $2 outAllMinus.bw
rm outAllMinus.wig

mv outUniqPlus.bw $3 
mv outUniqMinus.bw $4 
mv outAllPlus.bw $5 
mv outAllMinus.bw $6 
