#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 4 ]; then 
echo "usage v1: eap_run_tophat_long_ercc_pe tophatRefDir libraryId reads.fq out.bam"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Copy reads to local tmp file since will be making several passes
cp $3 reads.fq.gz

# Using $1 as location of genome indexes, ERCC as base containing the spikein index, align reads
tophat --no-discordant --no-mixed -p 8 -z0 --min-intron-length 20 --max-intron-length 1000000 \
       --read-mismatches 4 --read-edit-dist 4 --max-multihits 20 --library-type fr-firststrand \
       --transcriptome-index $1/annotation/gencode.v19 \
   --min-anchor-length 8 --splice-mismatches 0 --read-gap-length 2 \
   --mate-inner-dist 50 --mate-std-dev 20 --segment-length 25 \
   --b2-L 20 --b2-N 0 --b2-D 15 --b2-R 2 \
       $1/ERCC reads.fq.gz

# Building a new header
HD="@HD\tVN:1.4\tSO:coordinate" 
stCommand="perl tophat_bam_xsA_tag_fix.pl tophat_out/accepted_hits.bam | samtools view -bS - -o - | samtools sort -m10G - sortedFixedMapped; samtools merge -h newHeader.sam mergedSortedFixed.bam sortedFixedMapped.bam tophat_out/unmapped.bam"
newPG="@PG\tID:Samtools\tPN:Samtools\tCL:"$stCommand"\tPP:Tophat\tVN:VN:0.1.19-96b5f2294a"
libraryId="@CO\tLIBID:$2"

samtools view -H tophat_out/accepted_hits.bam | \
gawk -v HD="$HD" -v newPG="$newPG" -v library="$libraryId" \
   '{     if ($0 ~ /^@PG/) {PG=$0} 
     else if ($0 ~ /^@HD/) {print HD; }
     else if($0 ~ /^@SQ/) {print $0};
    }; END{print newPG"\n"PG"\n"library;}' > newHeader.sam
           
# Add reference genome specific accessions to header
cat $1/ERCC_COfile.txt >> newHeader.sam

# sort before merge

# fix unmapped bam and sort before merge
perl ${EAP_TOOLS_DIR}/tophat_bam_xsA_tag_fix.pl tophat_out/accepted_hits.bam | \
                      samtools view -bS - | samtools sort -m10G - sortedFixedMapped

# merge aligned and unaligned into single bam, using the patched up header
samtools merge -h newHeader.sam mergedSortedFixed.bam sortedFixedMapped.bam tophat_out/unmapped.bam
samtools index mergedSortedFixed.bam

# remove some larger files:
#rm reads1.fq.gz tmp2.fq.gz sorted.bam sortedFixedMapped.bam tophat_out/accepted_hits.bam

mv mergedSortedFixed.bam $4
mv mergedSortedFixed.bam.bai $4.bai

