#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 10 ]; then 
echo "usage v2: eap_run_star_long_pe starRefIndexDir chromFile libraryId read1.fq.gz read2.fq.gz \\"
echo "          outStarGenome.bam outAllMinus.bw outAllPlus.bw outUniqMinus.bw outUniqPlus.bw"
echo "Makes temp files so should be run in a freshly created directory."
exit -1; fi

# Expected versions:
# package(tool): uniformAnalysis(eap_run_star_long_pe) [version: v1.0(v2)]
# tool: STAR [version: 2.4.0]
# tool: samtools [version: 0.1.19-96b5f2294a]
# package(tool): ucscUtils(bedGraphToBigWig) [version: v293(v4)]

# Label parameters and copying input(s) to local tmp dir
starRefIndexDir=$1     # Directory containing STAR generated index on genome and spike-in
chromFile=$2           # Chrom info file for the genome and gender
libraryId=$3           # Accession ID (or other identifier) of bio-sample used to generate fastq(s)
cp $4 read1.fq.gz      # INPUT: gzipped fastq of read1 of paired-end reads
cp $5 read2.fq.gz      # INPUT: gzipped fastq of read2 of paired-end reads
outStarGenomeBam=$6    # OUTPUT: reads aligned to whole genome by STAR (*.bai is also generated)
outAllMinusBw=$7       # OUTPUT: bigWig signal of unique and multi-mapped minus-strand reads
outAllPlusBw=$8        # OUTPUT: bigWig signal of unique and multi-mapped plus-strand reads
outUniqMinusBw=$9      # OUTPUT: bigWig signal of uniquely mapped minus-strand reads
outUniqPlusBw=$10      # OUTPUT: bigWig signal of uniquely mapped plus-strand reads

# samtools command, library and COfile will be folded into bam header
samtoolsCommand="samtools view -buS - | samtools sort -m10G - sorted"
libraryComment="@CO\tLIBID:${libraryId}"
echo -e ${libraryComment} > COfile.txt
cat ${starRefIndexDir}/COfile.txt >> COfile.txt

# Note: in order to run on cluster, using:
# - STAR symlinked to STARstatic, 
# - --genomeLoad NoSharedMemory (instead of LoadAndRemove) 
# - 32g ram, 12 cpus.

# Run star for pair-end and stranded reads.
STAR --genomeDir ${starRefIndexDir} --readFilesIn read1.fq.gz read2.fq.gz           \
     --readFilesCommand zcat --runThreadN 12 --genomeLoad NoSharedMemory             \
     --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1       \
     --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04                     \
     --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000            \
     --outSAMheaderCommentFile COfile.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate      \
     --outSAMunmapped Within --outFilterType BySJout                                      \
     --outSAMheaderPG @PG ID:Samtools PN:Samtools CL:"${samtoolsCommand}" PP:STAR VN:VN:0.1.19-96b5f2294a \
     --outWigStrand Stranded --outSAMattributes NH HI --outSAMtype BAM SortedByCoordinate

samtools index Aligned.out.sortedByCoord.bam

# bedGrah to bigWig conversions
bedGraphToBigWig Signal.UniqueMultiple.str+.bg ${chromFile} signalAllPlus.bw
bedGraphToBigWig Signal.Unique.str-.bg ${chromFile} signalUniqPlus.bw
bedGraphToBigWig Signal.UniqueMultiple.str-.bg ${chromFile} signalAllMinus.bw
bedGraphToBigWig Signal.Unique.str-.bg ${chromFile} signalUniqMinus.bw

# remove some larger files:
rm read1.fq.gz read2.fq.gz

# deliver results:
mv Aligned.out.sortedByCoord.bam ${outStarGenomeBam}
mv Aligned.out.sortedByCoord.bam.bai ${outStarGenomeBam}.bai
mv signalAllMinus.bw ${outAllMinusBw}
mv signalAllPlus.bw ${outAllPlusBw}
mv signalUniqMinus.bw ${outUniqMinusBw}
mv signalUniqPlus.bw ${outUniqPlusBw}

# make sure star log is recorded.
cat Log.final.out

