#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message

# Check command line and provide usage and version information
if [ $# -ne 5 ];
then echo "usage: eap_run_hotspot input.bam genome dataType readLength outDir"
echo version: 1; 
echo Makes temp files so should be run in a freshly created directory .
exit -1; fi

python /cluster/home/mmaddren/grad/uniformAnalysis/standalone/hotspot.py /hive/groups/encode/encode3/tools/hotspot-distr-v4/ /hive/groups/encode/encode3/tools/bedtools-2.17.0/ /hive/groups/encode/encode3/tools/bedops/ $1 $2 $3 $4 `pwd` `pwd`

unstarch density.bed.starch > density.bed
intersectBed -a density.bed -b "/hive/groups/encode/encode3/tools/hotspot-distr-v4/data/"$2".K"$4".mappable_only.bed" -f 1.00 | cut -f 1,2,3,5> density.bedGraph
bedGraphToBigWig density.bedGraph "/hive/groups/encode/encode3/tools/gcap/GCAP-master/gcap/chromInfo_"$2".txt" density.bigWig

mv density.bigWig $5"/density.bigWig"
mv broadPeaks.bed $5"/broadPeaks.bed"
mv broadPeaksFdr.bed $5"/broadPeaksFdr.bed"
mv narrowPeaks.bed $5"/narrowPeaks.bed"		
