#!/bin/bash -ex
# Run bash with -e exit on first error, -x add +command stream to sterr.
# Remove -x for cleaner usage message
#
# This script calls peaks on a ChIP-seq bam file (with control bam) using SPP
# The arguments are:
# $1 - target genome
# $2 - chIP bam file to analyze
# $3 - control bam file
# $4 - output narrowPeak filename

# Check command line and provide usage and version information
if [ $# -ne 4 ];
then echo "usage v1: eap_run_spp_chip_se target chip.bam input.bam out.narrowPeak.bigBed"
echo target is ucsc database ID - hg19 or hg38 or mm10 most commonly at time of writing.
echo Makes temp files so should be run in a freshly created directory .
exit -1; fi

# TODO: manage script path better
tooldir=/hive/groups/encode/encode3/tools/phantompeakqualtools

# Run SPP with relaxed threshold on $2
Rscript $tooldir/run_spp.R -c=$2 -i=$3 -odir=. -savn=tmp.narrowPeak -npeak=300000 -tmpdir=.

# Convert narrowPeak file to narrowPeak.bb format in $4, checking chromosome coords vs $1
zcat tmp.narrowPeak.gz | sort -k1,1 -k2,2 > tmp.sorted
eap_narrowPeak_to_bigBed $1 tmp.sorted $4

# Remove temp files
rm -f tmp.narrowPeak.gz tmp.sorted
